### ISSUE TITLE
Mouse-overs for chart markers cut off long x-axis labels

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#387] opened 2022-08-16 20:25 UTC
The map and bar chart seem to be working correctly however, it seems as if x axis label is cut off
<img width="871" alt="Screen Shot 2022-08-16 at 2 34 58 PM" src="https://user-images.githubusercontent.com/62298921/184953927-91471823-11bd-464a-b814-8552bfdd1cf3.png">

_Originally posted by @sweverschulman in https://github.com/VEuPathDB/web-eda/issues/1313#issuecomment-1217006746_

This might be a web-eda issue, but I put it here for now.

Note that we can't have mouse-over ellipsis expansion on something that's already a mouse-over.  Could be tricky to solve!

**Comment by dmfalke** [comment] 2022-08-18 03:49
This is a duplicate of https://github.com/VEuPathDB/web-components/issues/386

**Closed by dmfalke** 2022-08-18 03:49 UTC

**Comment by SheenaTomko** [comment] 2022-08-19 19:00
Changed to only show the total count, entity type was removed. Looks good
